spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql3000.mochahost.com:3306/yamireh_palservice?serverTimezone=UTC
    username: yamireh
    password: yousef87
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true