spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://palservicedb.crjkd697whfb.us-west-2.rds.amazonaws.com/yousefDB
    username: yousef
    password: Yousef87
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true